---
- name: service | php-fpm | started
  service:
    name: "php{{ php_services_postfix }}-fpm"
    state: started

- name: service | php-fpm | stopped
  service:
    name: "php{{ php_services_postfix }}-fpm"
    state: stopped

- name: service | php-fpm | restarted
  service:
    state: restarted
    name: "php{{ php_services_postfix }}-fpm"

- name: service | php-fpm | reloaded
  service:
    state: reloaded
    name: "php{{ php_services_postfix }}-fpm"
